### ISSUE TITLE
Error when trying to build a version

### ISSUE THREAD

**Issue by marksev1** [styluslabs/maps#4]
It's possibly a noob issue, but can you help me with this:

(base) markos@toplakz:/media/toplakz/HDD1/nekakoda/maps$ make linux
cmake -H. -Bbuild/Release -DCMAKE_BUILD_TYPE=Release -DTANGRAM_PLATFORM=linux -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE 
-- Using gcc 9.4.0
-- USE CXX11_ABI
-- Using X11 for window creation
nfd Platform: PLATFORM_LINUX
nfd Compiler: COMPILER_GNU
Using DBUS version: 1.12.16
-- Use vcpkg: OFF
-- Build type configuration: Release
CMake Error at tangram-es/core/deps/sqlite3/CMakeLists.txt:10 (file):
  file does not recognize sub-command ARCHIVE_EXTRACT

CMake Error at tangram-es/core/deps/sqlite3/CMakeLists.txt:11 (file):
  file RENAME failed to rename

    /media/toplakz/HDD1/nekakoda/maps/tangram-es/core/deps/sqlite3/sqlite-amalgamation-3320300/sqlite3.h

  to

    /media/toplakz/HDD1/nekakoda/maps/tangram-es/core/deps/sqlite3/sqlite3.h

  because: No such file or directory

CMake Error at tangram-es/core/deps/sqlite3/CMakeLists.txt:12 (file):
  file RENAME failed to rename

    /media/toplakz/HDD1/nekakoda/maps/tangram-es/core/deps/sqlite3/sqlite-amalgamation-3320300/sqlite3.c

  to

    /media/toplakz/HDD1/nekakoda/maps/tangram-es/core/deps/sqlite3/sqlite3.c

  because: No such file or directory

-- Configuring incomplete, errors occurred!
See also "/media/toplakz/HDD1/nekakoda/maps/build/Release/CMakeFiles/CMakeOutput.log".
See also "/media/toplakz/HDD1/nekakoda/maps/build/Release/CMakeFiles/CMakeError.log".
make: *** [Makefile:57: cmake-linux] Error 1

**Comment by pbsurf** [comment]
In https://github.com/pbsurf/maps/blob/master/core/deps/sqlite3/CMakeLists.txt sqlite is downloaded and unzipped using `file ARCHIVE_EXTRACT`, added in cmake 3.18 - is your cmake version older than this?  You could manually unzip sqlite and move sqlite3.c and .h to the sqlite3 folder.

**Comment by pbsurf** [comment]
Installing glfw headers should fix this one - `sudo apt install libglfw3-dev` on Debian/Ubuntu

**Comment by marksev1** [comment]
Works, thanks...Where would you prefer to be contacted besides Github for some questions and observations regarding usage?
